apiVersion: v1
kind: Service
metadata:
{{- if .Values.service.name }}
  name: {{ .Values.service.name }}
{{- else }}
  name: {{ template "fullname" . }}
{{- end }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
{{- if .Values.service.annotations }}
  annotations:
{{ toYaml .Values.service.annotations | indent 4 }}
{{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.externalPort }}
    targetPort: {{ .Values.service.internalPort }}
    protocol: TCP
    name: http
  selector:
    app: {{ template "fullname" . }}
---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: {{ .Values.service.name }}-gateway
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: {{ .Values.service.istioPort }}
      name: http
      protocol: HTTP
    hosts:
    - "*"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ .Values.service.name }}-virtualservice
spec:
  hosts:
  - "*"
  gateways:
  - {{ .Values.service.name }}-gateway
  http:
  - match:
    - uri:
        prefix: /{{ .Values.service.name }}
    route:
    - destination:
        host: {{ .Values.service.name }}
        port:
          number: {{ .Values.service.externalPort }}
